# Generated by Django 5.1 on 2024-08-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_placeholder_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='placeholders',
        ),
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='pages.page')),
            ],
        ),
    ]
