# Generated by Django 5.1 on 2024-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_page_placeholders_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
