# Generated by Django 5.1 on 2024-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_show_in_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholder',
            name='image_value',
            field=models.ImageField(blank=True, null=True, upload_to='placeholders/'),
        ),
    ]
